![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [33]:
import numpy as np
my_array = np.arange(10)
print(my_array)


[0 1 2 3 4 5 6 7 8 9]


In [32]:
print(my_array[10:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [16]:
print(my_array[-2:-4:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [27]:

print(np.flip(my_array)[7:10])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [29]:
matriz = np.arange(1,21).reshape(4, 5)
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [31]:
print(np.flip(matriz))

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [35]:
print(matriz[:2, :2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [49]:
impares = matriz[np.array(matriz %2 != 0)]
print(impares.reshape(2, 5)[:2, :3])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [62]:
print(matriz[:3][::, ::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [66]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filtro = np.array(x == 'Loro')
print(filtro)
print(x[filtro])

[ True False False  True False]
['Loro' 'Loro']


In [70]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
filtro = np.where(x == 'Loro', True, False)
print(filtro)
print(x[filtro])

[ True False False  True False]
['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [88]:
secuencia = np.arange(20).reshape(10,2)
transformada = np.array(np.vsplit(secuencia, [5]))
print(transformada)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [90]:
matriz = np.arange(1,21).reshape(4, 5)
print(np.flip(matriz))


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [102]:
array = np.zeros((10))
print(array)
print(f"Tamaño que ocupa en bytes el array es: {array.nbytes}")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tamaño que ocupa en bytes el array es: 80


In [103]:
array[3] = 1
print(array)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [107]:
vector = np.arange(10,50)
print(vector)
print(np.flip(vector))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [117]:
vector = np.array([1,2,0,0,4,0])
print(np.nonzero(vector)[0])

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [128]:
matriz = np.random.randint(100, size = (10,10))
print(matriz)
print(f"Mínimo: {np.min(matriz)}")
print(f"Máximo: {matriz.max()}")

[[61 69 56 65 40 45 13 63 13  7]
 [57  7 13 18 48  6 81 91 68 32]
 [97 96 37 75  2 50 62 60 22 84]
 [78 67 59 78 50 49 27 42 57 39]
 [ 2 95 22  6 68 28 12 90 97 69]
 [97 48 73 55 60 42 76 38 34  6]
 [59 23 71  2  6 90 37 66 72 78]
 [77 60 83 46  5 64 17 15 70 10]
 [33 32 39 37 56 40 13 93 84 83]
 [68 57 22  3 51 87 66 58 74 15]]
Mínimo: 2
Máximo: 97


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [138]:
vector = np.random.random(size = 30)
print(vector)
print(vector.mean())

[0.08552646 0.23185283 0.19871361 0.10611896 0.46018031 0.45352421
 0.27574192 0.68132286 0.72942261 0.67517129 0.17501422 0.18383462
 0.56575752 0.29980786 0.63225001 0.04756799 0.27415843 0.15201899
 0.24506502 0.36169257 0.71412958 0.2604313  0.22450916 0.20517183
 0.52396834 0.70922924 0.33249271 0.60774709 0.68600297 0.07585236]
0.37247589562181976


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [160]:
array = np.ones((5,5))
print(array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [159]:
for index, fila in enumerate(array):
    if index != 0 and index != len(array)-1:
        fila[1:-1] = 0

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [202]:
array = np.zeros((8,8), np.int8)

for index, fila in enumerate(array):
    for j, valor in enumerate(fila):
        if (index % 2 != 0 and j % 2 == 0):
            array[index][j] = 1
        if (index % 2 == 0 and j % 2 != 0):
            array[index][j] = 1
    
print(array)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [203]:
array = np.ones((8,8), np.int8)
array[::2, ::2] = 0
array[1::2, 1::2] = 0
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [204]:
x = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [208]:
matriz = np.random.randint(30, size = (5,5))
media = np.mean(matriz)
desviacion = np.std(matriz)
print(matriz)
matriz = (matriz - media) / desviacion
print(matriz)

[[ 5  3  6 11  0]
 [15 24 24  5  0]
 [23 20 25 29  8]
 [ 3 28 19 15 18]
 [ 5 27 12  2 12]]
[[-0.91163756 -1.12463699 -0.80513785 -0.27263927 -1.44413614]
 [ 0.15335959  1.11185703  1.11185703 -0.91163756 -1.44413614]
 [ 1.00535731  0.68585817  1.21835674  1.6443556  -0.59213842]
 [-1.12463699  1.53785589  0.57935845  0.15335959  0.47285874]
 [-0.91163756  1.43135617 -0.16613956 -1.23113671 -0.16613956]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [214]:
secuencia = np.arange(11)
print(secuencia)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [215]:
secuencia2 = secuencia.copy()
secuencia2[4:8] = -1
print(secuencia2)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


In [217]:
secuencia3 = secuencia.copy()
secuencia3[4:8] *= -1
print(secuencia3)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [409]:
tablero = np.full(fill_value = ' ', shape = (10, 10))
print(tablero)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [410]:
tablero[0:2, 1] = 'O'
tablero[1, 3:7] = 'O'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'O' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [411]:
tablero[1, 4] = 'X'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [412]:
tablero[3, 8] = '-'
print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]


In [413]:
import random


def buscar_posicion_inicial():
    return np.random.randint(10, size = 2)


def posicionar_barco(coordenadas):
    orientacion = random.choice(['N', 'S', 'E', 'O'])
    
    if 'N' == orientacion:
        posible_barco = tablero[coordenadas[0]:coordenadas[0] - 4:-1, coordenadas[1]]
        if coordenadas[0] > 3 and 'O' not in posible_barco:
            tablero[coordenadas[0] - 4:coordenadas[0], coordenadas[1]] = 'O'
            return True
    elif 'S' == orientacion:
        posible_barco = tablero[coordenadas[0]:coordenadas[0] + 4, coordenadas[1]]
        if coordenadas[0] < 7 and 'O' not in posible_barco:
            tablero[coordenadas[0]:coordenadas[0] + 4, coordenadas[1]] = 'O'
            return True
    elif 'E' == orientacion:
        posible_barco = tablero[coordenadas[0], coordenadas[1]: coordenadas[1] + 4]
        if coordenadas[1] < 7 and 'O' not in posible_barco:
            tablero[coordenadas[0], coordenadas[1]:coordenadas[1] + 4] = 'O'
            return True
    elif 'O' == orientacion:
        posible_barco = tablero[coordenadas[0], coordenadas[1]: coordenadas[1] - 4:-1]
        if coordenadas[1] > 3 and 'O' not in posible_barco:
            tablero[coordenadas[0], coordenadas[1] - 4:coordenadas[1]] = 'O'
            return True
    return False


posicion_inicial = buscar_posicion_inicial()

while posicionar_barco(posicion_inicial) == False:
    posicion_inicial = buscar_posicion_inicial()

print(tablero)

[[' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 'O' ' ' 'O' 'X' 'O' 'O' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' 'O' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']]
